[project]
name = "second-homework"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "dataclasses>=0.8",
    "editdistance>=0.8.1",
    "egg",
    "h5py>=3.14.0",
    "ipykernel>=6.31.0",
    "matplotlib>=3.9.4",
    "numpy==1.23.5",
    "pandas>=2.1.0",
    "pytest>=8.4.2",
    "rich>=14.2.0",
    "scikit-learn>=1.6.1",
    "scipy>=1.13.1",
    "submitit>=1.5.3",
    "torch>=1.1.0",
    "torchmetrics>=1.8.2",
    "torchvision>=0.23.0",
    "tqdm>=4.67.1",
    "wandb>=0.23.1",
]

[tool.uv.sources]
egg = { git = "https://github.com/facebookresearch/EGG.git" }